export default {
  USER_INFO_RECEIVED: 'USER_INFO_RECEIVED',
  SELECTED_USER_ACCOUNT: 'SELECTED_USER_ACCOUNT',
  RESET_STATE: 'RESET_STATE',
  LOCATION_ADDRESS: 'LOCATION_ADDRESS',
  CATEGORIES_LIST: 'CATEGORIES_LIST',
  HIDE_CARD_NUMBER: 'HIDE_CARD_NUMBER',
  SHOW_CARD_NUMBER: 'SHOW_CARD_NUMBER',
  LIMIT: 'LIMIT',
};
